apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: home-assistant-integrations
  template:
    metadata:
      labels:
        app: home-assistant-integrations
    spec:
      containers:
        - name: home-assistant-integrations
          image: public.ecr.aws/axatol/home-assistant-integrations:latest
          env:
            - name: ZEVERSOLAR_TLC5000_ENDPOINT
              value: http://192.168.1.44/home.cgi
            - name: HUAWEI_HG659_ENDPOINT
              value: http://192.168.1.1
            - name: MQTT_ENDPOINT
              value: tcp://k8s.axatol.xyz:31883
          ports:
            - name: http
              containerPort: 8000
