name: CI

on:
  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/home-assistant-integrations

jobs:
  build:
    name: Build
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-${{ github.event.repository.name }}-${{ github.job }}-${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.image }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}
